# Change these first
owner: thegreatgulper # Your GitHub organization or username, where this repository lives
repo: checksitestatus # The name of this repository
assignees:
  - thegreatgulper

sites:
  - name: llslogistics.co.uk
    url: https://llslogistics.co.uk/
  - name: intuition-it.com
    url: https://www.intuition-it.com/
  - name: londonlaboursupply.devhug.uk
    url: https://londonlaboursupply.devhug.uk/
  - name: taptrip.com/
    url: https://taptrip.com/
  - name: pitsafe.com/
    url: https://pitsafe.com/
  - name: crownstonesurveyors.com/
    url: https://crownstonesurveyors.com/
  - name: crownstonegroup.co.uk/
    url: https://crownstonegroup.co.uk/
  - name: chivaree.co.uk/
    url: https://chivaree.co.uk/
  - name: galleonpropertysearch.com
    url: https://galleonpropertysearch.com
  - name: www.careerkatalyst.com/
    url: https://www.careerkatalyst.com/
  - name: www.linkmeup.org.uk/
    url: https://www.linkmeup.org.uk/
  - name: dynamiteevents.co.uk/
    url: https://dynamiteevents.co.uk/
  - name: iamsquarehead.com/
    url: https://iamsquarehead.com/
  - name: birkingroup.co.uk/
    url: https://www.birkingroup.co.uk/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /checksitestatus
  logoUrl: https://images.squarespace-cdn.com/content/v1/5ba4cded7980b349c9cdf2e3/1542366490843-UK5M696URGMCEGBHQIB6/hug-london-logo.png?format=1500w
  name: HUG status pages
  introTitle: "**HUG status pages** is the uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data. 
  navbar:
    - title: Status
      href: https://thegreatgulper.github.io/checksitestatus/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
